spring:
  application:
    name: Prueba tecnica Hang Xing
  datasource:
    url: jdbc:postgresql://localhost:5432/ohmycode
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false



